// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNV_IetM80sTqVBZGbZWQtds0LxAzeBFQ',
    appId: '1:226582123133:web:92baf048f911b3c53d1714',
    messagingSenderId: '226582123133',
    projectId: 'social-media-78bf9',
    authDomain: 'social-media-78bf9.firebaseapp.com',
    storageBucket: 'social-media-78bf9.appspot.com',
    measurementId: 'G-4ESNXJDFFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQo8VOK1Rl2GFUJGnXzk30ddzsuw6b84U',
    appId: '1:226582123133:android:fdd2f210e7b6af533d1714',
    messagingSenderId: '226582123133',
    projectId: 'social-media-78bf9',
    storageBucket: 'social-media-78bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmuauZ_l8AnbTEZXIROjK1W9O60Sthio',
    appId: '1:226582123133:ios:a69c96da3bc70a093d1714',
    messagingSenderId: '226582123133',
    projectId: 'social-media-78bf9',
    storageBucket: 'social-media-78bf9.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmuauZ_l8AnbTEZXIROjK1W9O60Sthio',
    appId: '1:226582123133:ios:a69c96da3bc70a093d1714',
    messagingSenderId: '226582123133',
    projectId: 'social-media-78bf9',
    storageBucket: 'social-media-78bf9.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNV_IetM80sTqVBZGbZWQtds0LxAzeBFQ',
    appId: '1:226582123133:web:a86cc7435f727ea73d1714',
    messagingSenderId: '226582123133',
    projectId: 'social-media-78bf9',
    authDomain: 'social-media-78bf9.firebaseapp.com',
    storageBucket: 'social-media-78bf9.appspot.com',
    measurementId: 'G-RSYMB1W536',
  );
}
